### ISSUE TITLE
README looks like a lab.

### ISSUE THREAD

**Issue by timothylevi** [learn-co-curriculum/pfwtfp-bug-fix-part-1#3]
Both `spec` and `lib` directories exist although this is not a lab.

#staff

**Comment by sgharms** [comment]
@timothylevi We enable the spec to trick Learn into providing the IDE environment for experimentation / debugging. The Sandbox is a per-batch setting. Is it safe to turn this into a straight README? Or do we want Learn to offer an IDE environment here (presumably they're off IDE interfaces by this point...but this lesson might ought be portable)

**Comment by timothylevi** [comment]
Just caught this @sgharms. Students will be off of the IDE, at least in the in-person program. Not sure how flexible we want this to be for this lab, but willing to leave it as is if we need this lab to work for students that would also use IDE.
